version: '3'
services:
  backend:
    image: bhaveshpchavda/traffic-sign-backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production

  frontend:
    image: bhaveshpchavda/traffic-sign-frontend:latest
    container_name: frontend
    ports:
      - "80:80"  # Map NGINX container port 80 to host port 80
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
